addons:
  postgresql: 9.6
  apt:
    packages:
      - docker-ce
cache:
  bundler: true
  directories:
    - $HOME/docker
before_cache:
  # Save tagged docker images
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'
before_install:
  # Load cached docker images
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
before_script:
  - mkdir tmp/db/postgres-data -p
  - mkdir tmp/log -p
  - cp config/deploy/travis-ci/database.yml config/database.yml
  - cp config/deploy/travis-ci/config.yml config/config.yml
  - cp config/deploy/travis-ci/secrets.yml config/secrets.yml
  - cp config/deploy/travis-ci/Dockerfile ../
  - cp config/deploy/travis-ci/docker-compose.yml ../
  - psql -c 'create database travis_ci_test;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - sudo docker-compose build
  - sudo docker-compose run salsa rake db:create
  - sudo docker-compose run salsa rake db:schema:load
  - sudo docker-compose run salsa rake db:migrate
  - sudo docker-compose run salsa rake db:seed

script:
  - sudo docker-compose run salsa rake db:schema:load RAILS_ENV=test
  - sudo docker-compose run salsa rake db:migrate RAILS_ENV=test
  - sudo docker-compose run salsa bash ./cucumber.sh

after_script:
  - sudo docker-compose run salsa bash ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT --prefix /home/apps/salsa -r bff7805609100c597affe2b7103b64a96d4222fe74ad2675097a937591d8695c

dist: trusty
language: ruby
rvm:
  - 2.4.1
services:
  - redis-server
sudo: required
