development:
  adapter: postgresql
  encoding: unicode
  database: salsa_development
  host: db
  username: postgres
  password:
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: salsa_test
  host: db
  username: postgres
  password:
  pool: 5
